server:
  port: 8808

spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  application:
    name: social-room
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
#    password : 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  devtools:
#    add-properties:
#    password : 1234
#eureka :
#  instance :
#    instance-id : ${spring.application.name}:${spring.application.instance-id:${random.value}}
#  client:
#    register-with-eureka : true
#    fetch-registry : true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
spring.devtools.livereload.enabled: false


